
export const MOVIE_DETAIL_FETCH_REQUESTED = 'MOVIE_DETAIL_FETCH_REQUESTED';
export const MOVIE_DETAIL_FETCH_FULLFILLED = 'MOVIE_DETAIL_FETCH_FULLFILLED';
export const MOVIE_DETAIL_FETCH_REJECTED = 'MOVIE_DETAIL_FETCH_REJECTED';

export const MOVIE_CREDITS_FETCH_REQUESTED = 'MOVIE_CREDITS_FETCH_REQUESTED';
export const MOVIE_CREDITS_FETCH_FULLFILLED = 'MOVIE_CREDITS_FETCH_FULLFILLED';
export const MOVIE_CREDITS_FETCH_REJECTED = 'MOVIE_CREDITS_FETCH_REJECTED';

export const MOVIE_REVIEWS_FETCH_REQUESTED = 'MOVIE_REVIEWS_FETCH_REQUESTED';
export const MOVIE_REVIEWS_FETCH_FULLFILLED = 'MOVIE_REVIEWS_FETCH_FULLFILLED';
export const MOVIE_REVIEWS_FETCH_REJECTED = 'MOVIE_REVIEWS_FETCH_REJECTED';

export const MOVIE_RECOMMENDATIONS_FETCH_REQUESTED = 'MOVIE_RECOMMENDATIONS_FETCH_REQUESTED';
export const MOVIE_RECOMMENDATIONS_FETCH_FULLFILLED = 'MOVIE_RECOMMENDATIONS_FETCH_FULLFILLED';
export const MOVIE_RECOMMENDATIONS_FETCH_REJECTED = 'MOVIE_RECOMMENDATIONS_FETCH_REJECTED';

export const MOVIE_RELEASE_DATES_FETCH_REQUESTED = 'MOVIE_RELEASE_DATES_FETCH_REQUESTED';
export const MOVIE_RELEASE_DATES_FETCH_FULLFILLED = 'MOVIE_RELEASE_DATES_FETCH_FULLFILLED';
export const MOVIE_RELEASE_DATES_FETCH_REJECTED = 'MOVIE_RELEASE_DATES_FETCH_REJECTED';

export const MOVIE_KEYWORDS_FETCH_REQUESTED = 'MOVIE_KEYWORDS_FETCH_REQUESTED';
export const MOVIE_KEYWORDS_FETCH_FULLFILLED = 'MOVIE_KEYWORDS_FETCH_FULLFILLED';
export const MOVIE_KEYWORDS_FETCH_REJECTED = 'MOVIE_KEYWORDS_FETCH_REJECTED';

export const MOVIE_IMAGES_FETCH_REQUESTED = 'MOVIE_IMAGES_FETCH_REQUESTED';
export const MOVIE_IMAGES_FETCH_FULLFILLED = 'MOVIE_IMAGES_FETCH_FULLFILLED';
export const MOVIE_IMAGES_FETCH_REJECTED = 'MOVIE_IMAGES_FETCH_REJECTED';

export const MOVIE_VIDEOS_FETCH_REQUESTED = 'MOVIE_VIDEOS_FETCH_REQUESTED';
export const MOVIE_VIDEOS_FETCH_FULLFILLED = 'MOVIE_VIDEOS_FETCH_FULLFILLED';
export const MOVIE_VIDEOS_FETCH_REJECTED = 'MOVIE_VIDEOS_FETCH_REJECTED';


export default {
  MOVIE_DETAIL_FETCH_REQUESTED,
  MOVIE_DETAIL_FETCH_FULLFILLED,
  MOVIE_DETAIL_FETCH_REJECTED,

  MOVIE_CREDITS_FETCH_REQUESTED,
  MOVIE_CREDITS_FETCH_FULLFILLED,
  MOVIE_CREDITS_FETCH_REJECTED,

  MOVIE_REVIEWS_FETCH_REQUESTED,
  MOVIE_REVIEWS_FETCH_FULLFILLED,
  MOVIE_REVIEWS_FETCH_REJECTED,

  MOVIE_RECOMMENDATIONS_FETCH_REQUESTED,
  MOVIE_RECOMMENDATIONS_FETCH_FULLFILLED,
  MOVIE_RECOMMENDATIONS_FETCH_REJECTED,

  MOVIE_RELEASE_DATES_FETCH_REQUESTED,
  MOVIE_RELEASE_DATES_FETCH_FULLFILLED,
  MOVIE_RELEASE_DATES_FETCH_REJECTED,

  MOVIE_KEYWORDS_FETCH_REQUESTED,
  MOVIE_KEYWORDS_FETCH_FULLFILLED,
  MOVIE_KEYWORDS_FETCH_REJECTED,

  MOVIE_IMAGES_FETCH_REQUESTED,
  MOVIE_IMAGES_FETCH_FULLFILLED,
  MOVIE_IMAGES_FETCH_REJECTED,

  MOVIE_VIDEOS_FETCH_REQUESTED,
  MOVIE_VIDEOS_FETCH_FULLFILLED,
  MOVIE_VIDEOS_FETCH_REJECTED,
};
