export const DETAIL_FETCH_REQUESTED = 'DETAIL_FETCH_REQUESTED';
export const DETAIL_FETCH_FULFILLED = 'DETAIL_FETCH_FULFILLED';
export const DETAIL_FETCH_REJECTED = 'DETAIL_FETCH_REJECTED';

export default {
  DETAIL_FETCH_REQUESTED,
  DETAIL_FETCH_FULFILLED,
  DETAIL_FETCH_REJECTED,
};
