export const MOVIE_DETAIL_FETCH_REQUESTED = 'MOVIE_DETAIL_FETCH_REQUESTED';
export const MOVIE_DETAIL_FETCH_FULFILLED= 'MOVIE_DETAIL_FETCH_FULFILLED';
export const MOVIE_DETAIL_FETCH_REJECTED = 'MOVIE_DETAIL_FETCH_REJECTED';

export default {
  MOVIE_DETAIL_FETCH_REQUESTED,
  MOVIE_DETAIL_FETCH_FULFILLED,
  MOVIE_DETAIL_FETCH_REJECTED
};
