export const MOVIE_DETAIL_FETCH = 'MOVIE_DETAIL_FETCH';
export const MOVIE_DETAIL_FETCH_CANCEL = 'MOVIE_DETAIL_FETCH_CANCEL';
export const MOVIE_DETAIL_FETCH_FULFILLED= 'MOVIE_DETAIL_FETCH_FULFILLED';
export const MOVIE_DETAIL_FETCH_REJECTED = 'MOVIE_DETAIL_FETCH_REJECTED';

export default {
  MOVIE_DETAIL_FETCH,
  MOVIE_DETAIL_FETCH_CANCEL,
  MOVIE_DETAIL_FETCH_FULFILLED,
  MOVIE_DETAIL_FETCH_REJECTED
}
