export const PERSON_FETCH_REQUESTED = 'PERSON_FETCH_REQUESTED';
export const PERSON_FETCH_FULFILLED = 'PERSON_FETCH_FULFILLED';
export const PERSON_FETCH_REJECTED = 'PERSON_FETCH_REJECTED';

export default {
  PERSON_FETCH_REQUESTED,
  PERSON_FETCH_FULFILLED,
  PERSON_FETCH_REJECTED
};
