export const PEOPLE_FETCH_REQUESTED = 'PEOPLE_FETCH_REQUESTED';
export const PEOPLE_FETCH_FULFILLED = 'PEOPLE_FETCH_FULFILLED';
export const PEOPLE_FETCH_REJECTED = 'PEOPLE_FETCH_REJECTED';

export default {
  PEOPLE_FETCH_REQUESTED,
  PEOPLE_FETCH_FULFILLED,
  PEOPLE_FETCH_REJECTED,
};
