export const DATA_FETCH_REQUESTED = 'DATA_FETCH_REQUESTED';
export const DATA_FETCH_FULFILLED = 'DATA_FETCH_FULFILLED';
export const DATA_FETCH_REJECTED = 'DATA_FETCH_REJECTED';

export default {
  DATA_FETCH_REQUESTED,
  DATA_FETCH_FULFILLED,
  DATA_FETCH_REJECTED,
};
