export const TVSHOWS_FETCH_REQUESTED = 'TVSHOWS_FETCH_REQUESTED';
export const TVSHOWS_FETCH_FULFILLED = 'TVSHOWS_FETCH_FULFILLED';
export const TVSHOWS_FETCH_REJECTED = 'TVSHOWS_FETCH_REJECTED';

export default {
  TVSHOWS_FETCH_REQUESTED,
  TVSHOWS_FETCH_FULFILLED,
  TVSHOWS_FETCH_REJECTED,
};
