export const MOVIE_FETCH_REQUESTED = 'MOVIE_FETCH_REQUESTED';
export const MOVIE_FETCH_FULFILLED = 'MOVIE_FETCH_FULFILLED';
export const MOVIE_FETCH_REJECTED = 'MOVIE_FETCH_REJECTED';

export default {
  MOVIE_FETCH_REQUESTED,
  MOVIE_FETCH_FULFILLED,
  MOVIE_FETCH_REJECTED,
};
