export const TVSHOW_DETAIL_FETCH_REQUESTED = 'TVSHOW_DETAIL_FETCH_REQUESTED';
export const TVSHOW_DETAIL_FETCH_FULFILLED = 'TVSHOW_DETAIL_FETCH_FULFILLED';
export const TVSHOW_DETAIL_FETCH_REJECTED = 'TVSHOW_DETAIL_FETCH_REJECTED';


export const CREDITS_FETCH_REQUESTED = 'CREDITS_FETCH_REQUESTED';
export const CREDITS_FETCH_FULLFILLED = 'CREDITS_FETCH_FULLFILLED';
export const CREDITS_FETCH_REJECTED = 'CREDITS_FETCH_REJECTED';

export const REVIEWS_FETCH_REQUESTED = 'REVIEWS_FETCH_REQUESTED';
export const REVIEWS_FETCH_FULLFILLED = 'REVIEWS_FETCH_FULLFILLED';
export const REVIEWS_FETCH_REJECTED = 'REVIEWS_FETCH_REJECTED';

export const RECOMMENDATIONS_FETCH_REQUESTED = 'RECOMMENDATIONS_FETCH_REQUESTED';
export const RECOMMENDATIONS_FETCH_FULLFILLED = 'RECOMMENDATIONS_FETCH_FULLFILLED';
export const RECOMMENDATIONS_FETCH_REJECTED = 'RECOMMENDATIONS_FETCH_REJECTED';

export const RELEASE_DATES_FETCH_REQUESTED = 'RELEASE_DATES_FETCH_REQUESTED';
export const RELEASE_DATES_FETCH_FULLFILLED = 'RELEASE_DATES_FETCH_FULLFILLED';
export const RELEASE_DATES_FETCH_REJECTED = 'RELEASE_DATES_FETCH_REJECTED';

export const KEYWORDS_FETCH_REQUESTED = 'KEYWORDS_FETCH_REQUESTED';
export const KEYWORDS_FETCH_FULLFILLED = 'KEYWORDS_FETCH_FULLFILLED';
export const KEYWORDS_FETCH_REJECTED = 'KEYWORDS_FETCH_REJECTED';

export const IMAGES_FETCH_REQUESTED = 'IMAGES_FETCH_REQUESTED';
export const IMAGES_FETCH_FULLFILLED = 'IMAGES_FETCH_FULLFILLED';
export const IMAGES_FETCH_REJECTED = 'IMAGES_FETCH_REJECTED';

export const VIDEOS_FETCH_REQUESTED = 'VIDEOS_FETCH_REQUESTED';
export const VIDEOS_FETCH_FULLFILLED = 'VIDEOS_FETCH_FULLFILLED';
export const VIDEOS_FETCH_REJECTED = 'VIDEOS_FETCH_REJECTED';

export const SEASON_FETCH_REQUESTED = 'SEASON_FETCH_REQUESTED';
export const SEASON_FETCH_FULLFILLED = 'SEASON_FETCH_FULLFILLED';
export const SEASON_FETCH_REJECTED = 'SEASON_FETCH_REJECTED';


export default {


  TVSHOW_DETAIL_FETCH_REQUESTED,
  TVSHOW_DETAIL_FETCH_FULFILLED,
  TVSHOW_DETAIL_FETCH_REJECTED,

  CREDITS_FETCH_REQUESTED,
  CREDITS_FETCH_FULLFILLED,
  CREDITS_FETCH_REJECTED,

  REVIEWS_FETCH_REQUESTED,
  REVIEWS_FETCH_FULLFILLED,
  REVIEWS_FETCH_REJECTED,

  RECOMMENDATIONS_FETCH_REQUESTED,
  RECOMMENDATIONS_FETCH_FULLFILLED,
  RECOMMENDATIONS_FETCH_REJECTED,

  RELEASE_DATES_FETCH_REQUESTED,
  RELEASE_DATES_FETCH_FULLFILLED,
  RELEASE_DATES_FETCH_REJECTED,

  KEYWORDS_FETCH_REQUESTED,
  KEYWORDS_FETCH_FULLFILLED,
  KEYWORDS_FETCH_REJECTED,

  IMAGES_FETCH_REQUESTED,
  IMAGES_FETCH_FULLFILLED,
  IMAGES_FETCH_REJECTED,

  VIDEOS_FETCH_REQUESTED,
  VIDEOS_FETCH_FULLFILLED,
  VIDEOS_FETCH_REJECTED,

  SEASON_FETCH_REQUESTED,
  SEASON_FETCH_FULLFILLED,
  SEASON_FETCH_REJECTED,

};
