export const PERSON_FETCH = 'PERSON_FETCH';
export const PERSON_FETCH_CANCEL = 'PERSON_FETCH_CANCEL';
export const PERSON_FETCH_FULFILLED = 'PERSON_FETCH_FULFILLED';
export const PERSON_FETCH_REJECTED = 'PERSON_FETCH_REJECTED';

export const INITIAL_STATE = {
  person: {},
  fetchStatus:''
};

export const actionTypes = {
  PERSON_FETCH,
  PERSON_FETCH_CANCEL,
  PERSON_FETCH_FULFILLED,
  PERSON_FETCH_REJECTED,
  INITIAL_STATE
};
