export const MENU_FETCH_REQUESTED = 'MENU_FETCH_REQUESTED';
export const MENU_FETCH_FULLFILLED = 'MENU_FETCH_FULLFILLED';
export const MENU_FETCH_REJECTED = 'MENU_FETCH_REJECTED';

export const SUB_MENU_FETCH_REQUESTED = 'SUB_MENU_FETCH_REQUESTED';
export const SUB_MENU_FETCH_FULLFILLED = 'SUB_MENU_FETCH_FULLFILLED';
export const SUB_MENU_FETCH_REJECTED = 'SUB_MENU_FETCH_REJECTED';

export default {
  MENU_FETCH_REQUESTED,
  MENU_FETCH_FULLFILLED,
  MENU_FETCH_REJECTED,

  SUB_MENU_FETCH_REQUESTED,
  SUB_MENU_FETCH_FULLFILLED,
  SUB_MENU_FETCH_REJECTED
};
