export const TVSHOWS_FETCH_REQUESTED = 'TVSHOWS_FETCH_REQUESTED';
export const TVSHOWS_FETCH_FULFILLED = 'TVSHOWS_FETCH_FULFILLED';
export const TVSHOWS_FETCH_REJECTED = 'TVSHOWS_FETCH_REJECTED';

export const TV_SHOW_GENRES_FETCH_REQUESTED = 'TV_SHOW_GENRES_FETCH_REQUESTED';
export const TV_SHOW_GENRES_FETCH_FULLFILLED = 'TV_SHOW_GENRES_FETCH_FULLFILLED';
export const TV_SHOW_GENRES_FETCH_REJECTED = 'TV_SHOW_GENRES_FETCH_REJECTED';

export const POPULAR = 'popular';
export const TOP_RATED = 'top_rated';
export const ON_THE_AIR = 'on_the_air';
export const AIRING_TODAY = 'airing_today';

export default {
  TVSHOWS_FETCH_REQUESTED,
  TVSHOWS_FETCH_FULFILLED,
  TVSHOWS_FETCH_REJECTED,

  TV_SHOW_GENRES_FETCH_REQUESTED,
  TV_SHOW_GENRES_FETCH_FULLFILLED,
  TV_SHOW_GENRES_FETCH_REJECTED,

  POPULAR,
  TOP_RATED,
  ON_THE_AIR,
  AIRING_TODAY
};
