
export const MOVIE_DETAIL_FETCH_REQUESTED = 'MOVIE_DETAIL_FETCH_REQUESTED';
export const MOVIE_DETAIL_FETCH_FULLFILLED = 'MOVIE_DETAIL_FETCH_FULLFILLED';
export const MOVIE_DETAIL_FETCH_REJECTED = 'MOVIE_DETAIL_FETCH_REJECTED';

export default {
  MOVIE_DETAIL_FETCH_REQUESTED,
  MOVIE_DETAIL_FETCH_FULLFILLED,
  MOVIE_DETAIL_FETCH_REJECTED
};
