
export const INITIAL_STATE = {
  movie: {},
  fetchStatus :''
};

export const MOVIE_DETAIL_FETCH = 'MOVIE_DETAIL_FETCH';
export const MOVIE_DETAIL_FETCH_CANCEL = 'MOVIE_DETAIL_FETCH_CANCEL';
export const MOVIE_DETAIL_FETCH_FULLFILLED = 'MOVIE_DETAIL_FETCH_FULLFILLED';
export const MOVIE_DETAIL_FETCH_REJECTED = 'MOVIE_DETAIL_FETCH_REJECTED';

export default {
  INITIAL_STATE,
  MOVIE_DETAIL_FETCH,
  MOVIE_DETAIL_FETCH_CANCEL,
  MOVIE_DETAIL_FETCH_FULLFILLED,
  MOVIE_DETAIL_FETCH_REJECTED
}
