export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FETCH_CANCEL = 'MOVIES_FETCH_CANCEL';
export const MOVIES_FETCH_FULFILLED = 'MOVIES_FETCH_FULFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export const actionTypes = {
  MOVIES_FETCH,
  MOVIES_FETCH_CANCEL,
  MOVIES_FETCH_FULFILLED,
  MOVIES_FETCH_REJECTED
};
