export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const MOVIES_FETCH_FULFILLED = 'MOVIES_FETCH_FULFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export default {
  MOVIES_FETCH_REQUESTED,
  MOVIES_FETCH_FULFILLED,
  MOVIES_FETCH_REJECTED
};
