

export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const MOVIES_FETCH_FULLFILLED = 'MOVIES_FETCH_FULLFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export const GENRES_FETCH_REQUESTED = 'GENRES_FETCH_REQUESTED';
export const GENRES_FETCH_FULLFILLED = 'GENRES_FETCH_FULLFILLED';
export const GENRES_FETCH_REJECTED = 'GENRES_FETCH_REJECTED';

export const CURRENT_FETCH_REQUESTED = 'CURRENT_FETCH_REQUESTED';
export const CURRENT_FETCH_FULLFILLED = 'CURRENT_FETCH_FULLFILLED';
export const CURRENT_FETCH_REJECTED = 'CURRENT_FETCH_REJECTED';

export default {
  MOVIES_FETCH_REQUESTED,
  MOVIES_FETCH_FULLFILLED,
  MOVIES_FETCH_REJECTED,

  GENRES_FETCH_REQUESTED,
  GENRES_FETCH_FULLFILLED,
  GENRES_FETCH_REJECTED,

  CURRENT_FETCH_REQUESTED,
  CURRENT_FETCH_FULLFILLED,
  CURRENT_FETCH_REJECTED
};
